language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
os: linux
dist: bionic
arch:
 - amd64
 - arm64
 - s390x
before_install:
  - sudo apt -y install zip nuitka
install:
  - pip install -r requirements.txt
script:
  - ./build
  - ./test