language: python
python:
  - "3.8"
  - "nightly"
os: linux
dist: bionic
arch:
 - amd64
 - arm64
before_install:
  - sudo apt -y install zip
install:
  - pip install -r requirements.txt
  - pip install nuitka
script:
  - ./build
  - ./test