language: python
python:
  - "3.7"
  - "3.8"
  - "nightly"
os: linux
dist: bionic
arch:
 - amd64
before_install:
  - wget -O - http://nuitka.net/deb/archive.key.gpg | sudo apt-key add -
  - echo "deb http://nuitka.net/deb/stable/bionic bionic main" | sudo tee /etc/apt/sources.list.d/nuitka.list
  - sudo apt update
  - sudo apt -y install zip nuitka
install:
  - pip install -r requirements.txt
script:
  - ./build
  - ./test