language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
os: linux
dist: bionic
arch:
  - amd64
before_install:
  - sudo apt -y install zip
install:
  - pip install -r requirements.txt
  - pip install nuitka
script:
  - ./build
  - ./test