#!/bin/bash

function build_nuitka {
    echo "Nuitka was found on your system."
    echo "Building an optimized binary..."
    nuitka3 --remove-output __main__.py -o pycracker.bin
}

function build_python {
    echo "Only ZIP was detected."
    echo "Building a normal Python ZIP..."
    zip -r pycracker.zip __main__.py pycracker -x "*__pycache__*"
}

function build_both {
    echo "Nuitka and ZIP were both detected."
    echo "Will use both"
    nuitka3 --remove-output __main__.py -o pycracker.bin
    zip -r pycracker.zip __main__.py pycracker -x "*__pycache__*"
}

if nuitka3 --version && zip --version; then
    build_both
elif nuitka3 --version; then
    build_nuitka
elif zip --version; then
    build_python
else
    echo "Neither zip or nuitka were found on your system!"
    echo "Giving up..."
    return 1
fi