#!/bin/bash

function build_nuitka {
    nuitka3 --remove-output __main__.py -o pycracker.bin
}

function build_python {
    zip -r pycracker.zip __main__.py pycracker -x "*__pycache__*"
}

function build_both {
    build_nuitka
    build_python
}

if nuitka3 --version || nuitka --version && zip --version; then
    echo "Nuitka and ZIP were both detected."
    echo "Will use both"
    build_both
elif [ nuitka3 --version || nuitka --version ]; then
    echo "Nuitka was found on your system."
    echo "Building an optimized binary..."
    build_nuitka
elif zip --version; then
    echo "Only ZIP was detected."
    echo "Building a normal Python ZIP..."
    build_python
else
    echo "Neither zip or nuitka were found on your system!"
    echo "Giving up..."
    return 1
fi